corpora_to_exclude:
  - SyntheticData
  - RenDissData
# hop=250 and window_len=1000 parameters are taken from musicbert
hop: 8
window_len: 128
repr_type: oct
aug_within_range: true
aug_within_range_n_keys: 12

aug_rhythms: false
