features:
  - chord_factors
  - chord_tone
  - harmony_onset
  - bass_pcs
  - spelling
  - primary_degree
  - primary_alteration
  - secondary_degree
  - secondary_alteration
  - inversion
  - mode
  - key
  - key_pc
  - quality
  - granular_key
  - granular_key_pc
  - granular_mode
  - scale_degree
  - scale_degree_step
  - scale_degree_alteration
  - key_signature
  - granular_key_signature
  - tonicization
concatenated_features:
  - [key_pc, mode]
  - [key_signature, mode]
  - [granular_key_pc, granular_mode]
  - [granular_key_signature, granular_mode]
  - [primary_alteration, primary_degree]
  - [secondary_alteration, secondary_degree]
  - [primary_alteration, primary_degree, secondary_alteration, secondary_degree]
corpora_to_exclude:
  - RenDissData
# hop=250 and window_len=1000 parameters are taken from musicbert
hop: 250
window_len: 1000
repr_type: oct
aug_by_key: true
aug_by_key_n_keys: 12

aug_rhythms: true
